<a href="https://colab.research.google.com/github/jigarbhalsod/ML-Launch/blob/main/18Sept25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1D MATRIX

In [ ]:
import numpy as np
a = np.random.randint(1,10,5)
# a*=100
a

array([5, 1, 4, 7, 5])

2D MATRIX

In [ ]:
b = np.random.randint(1,11,(5,5))
# b*=100
b

array([[ 8,  4,  1, 10,  6],
       [ 8,  3,  1,  9,  3],
       [ 5,  6,  3,  4,  5],
       [ 7,  2,  9,  6,  5],
       [ 4,  5,  5,  5,  7]])

Transpose, Magnitude, dot product, cross product

In [ ]:
print("a Transpose")
print(a.T)
print("\nb Transpose")
print(b.T)

print("\na and b Cross product")
print(np.cross(a[:3], b[0,:3]))
print("\na and b dot product")
print(np.dot(a,b))
a@b

a Transpose
[5 1 4 7 5]

b Transpose
[[ 8  8  5  7  4]
 [ 4  3  6  2  5]
 [ 1  1  3  9  5]
 [10  9  4  6  5]
 [ 6  3  5  5  7]]

a and b Cross product
[-15  27  12]

a and b dot product
[137  86 106 142 123]


array([137,  86, 106, 142, 123])

DETERMINANT AND INVERSE

In [ ]:
print("Determinant")
print(np.linalg.det(b))
print("Inverse")
print(np.linalg.inv(b))

print("Checking the laws")
# print((b @ np.linalg.inv(b), np.eye(5)))

Determinant
999.9999999999998
Inverse
[[ 0.62  -0.65   0.49   0.29  -0.81 ]
 [-0.536  0.52   0.028 -0.212  0.368]
 [-0.376  0.32  -0.152  0.008  0.288]
 [-0.564  0.73  -0.478 -0.238  0.682]
 [ 0.7   -0.75   0.15   0.15  -0.35 ]]
Checking the laws


CALCULUS

In [ ]:
def func1(x):
  return x**3+2*x
def derivative(func, x, h=1e-5):
  return (func(x+h)-func(x))/h
print("The derivative of f(x) with x=1 value")
print(derivative(func1, 1))

The derivative of f(x) with x=1 value
5.000030000124056


GREDIENT

In [ ]:
def func2(x,y):
  return x**2 + y**2
def gredient(func,x,y,h=1e-5):
  return (func(x+h,y)-func(x-h,y))/h,(func(x,y+h)-func(x,y-h))/h
print("The derivative of func2(x) with x=1 and y=1 value")
print(gredient(func2,1,1))

The derivative of func2(x) with x=1 and y=1 value
(4.000000000004, 4.000000000004)


PCA-like Decomposition

In [ ]:
x = np.linspace(0,10,10)
y = 2*x + 7 + np.random.normal(0,0.5,10)  # small noise
data = np.column_stack((x, y))
data

array([[ 0.        ,  6.94770023],
       [ 1.11111111,  9.25321101],
       [ 2.22222222, 12.17272174],
       [ 3.33333333, 13.58174986],
       [ 4.44444444, 15.50670673],
       [ 5.55555556, 17.66370126],
       [ 6.66666667, 21.1137486 ],
       [ 7.77777778, 22.37551744],
       [ 8.88888889, 24.39404684],
       [10.        , 26.93539565]])

Eigan Values Eigan Vectors

In [ ]:
cov = np.cov(data.T)
vals, vecs = np.linalg.eig(cov)
print("Coverience :")
print(cov)
print("Eigen values :")
print(vals)
print("Eigen vectors :")
print(vecs)

Coverience :
[[11.31687243 23.21927189]
 [23.21927189 47.77656222]]
Eigen values :
[2.61849445e-02 5.90672497e+01]
Eigen vectors :
[[-0.89931391 -0.43730365]
 [ 0.43730365 -0.89931391]]
