<a href="https://colab.research.google.com/github/jigarbhalsod/ML-Launch/blob/main/20Sept2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THIS IS BASICALLY A PRACTICE OF NUMPY AND PANDAS LIBRARY OF PYTHON FOR BASIC INTRODUCTION PURPOSE.

In [ ]:
import numpy as np

# Create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
print('x = ', x) # x = [1 2 3 4 5]
print('x has dimensions:', x.shape) # x has dimensions: (5,)
print('The elements in x are of type:', x.dtype) # The elements in x are of type: int64

# Create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('y = ', Y)
print('Y has dimensions:', Y.shape) # Y has dimensions: (4, 3)
print('Y has a total of', Y.size, 'elements') # Y has a total of 12 elements
print('Y is an object of type:', type(Y)) # Y is an object of type: class 'numpy.ndarray'
print('The elements in Y are of type:', Y.dtype) # The elements in Y are of type: int64

x =  [1 2 3 4 5]
x has dimensions: (5,)
The elements in x are of type: int64
y =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [ ]:
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [ ]:
x = np.arange(10)
print(x)
x = np.arange(4,10)
print(x)
x = np.arange(1,14,3)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [ ]:
x = np.linspace(0,25,10,endpoint=False)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])



*   linspace → define number of points.
*   arange → define step size.
*   linspace includes the endpoint by default; arange does not include the stop value.

In [ ]:
x = np.arange(20)
print('x = np.arange(20) :\n',x)
x = np.reshape(x, (4,5))
print('x = np.reshape(x, (4,5)) :\n',x)

x = np.arange(20).reshape(4, 5) # does the same thing as above

y = np.linspace(0,50,10,endpoint=False).reshape(5,2)
print('y = np.linspace(0,50,10,endpoint=False).reshape(5,2) :\n',y)

x = np.arange(20) :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
x = np.reshape(x, (4,5)) :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
y = np.linspace(0,50,10,endpoint=False).reshape(5,2) :
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


y = np.linspace(0, 50, 10, endpoint=False)<br>
Generates 10 evenly spaced numbers from 0 up to but not including 50 (endpoint=False).

.reshape(5, 2)<br>
Reshapes the 1D array of 10 numbers into a 2D array with 5 rows and 2 columns.

In [ ]:
X = np.arange(20).reshape(4, 5)
print('X = np.arange(20).reshape(4, 5):\n',X)
Z = X[1:4,2:5]
print('\nZ = X[1:4,2:5]:\n',Z)
Z = X[1:,2:]
print('\nZ = X[1:,2:]:\n',Z)

X = np.arange(20).reshape(4, 5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = X[1:4,2:5]:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Z = X[1:,2:]:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


SLICING TOPIC

In [ ]:
X = np.random.random((3,3))
X = np.round(X, 2)  # round to 2 decimal places
print('X = np.random.random((3,3)):\n',X)

X = np.random.randint(4,15,size=(3,2))
print('\nX = np.random.randint(4,15,size=(3,2)):\n',X)

X = np.random.normal(1, 0.1, size=(100,100))
print('\nX = np.random.normal(0, 0.1, size=(100,100)):\n',X)

X = np.random.random((3,3)):
 [[0.64 0.54 0.71]
 [0.16 0.97 0.02]
 [0.77 0.76 0.76]]

X = np.random.randint(4,15,size=(3,2)):
 [[ 5  5]
 [13 11]
 [ 6  7]]

X = np.random.normal(0, 0.1, size=(100,100)):
 [[1.01736306 0.98247615 0.85018157 ... 0.9093092  1.05149284 1.15062296]
 [1.19003742 0.91093313 0.86391372 ... 1.2042611  1.11880026 1.00194004]
 [0.96388479 0.89913465 0.90421875 ... 0.82286104 0.99425696 1.09705965]
 ...
 [1.00105205 0.94714358 1.05307236 ... 0.99969933 1.13172477 0.83614332]
 [1.18348243 0.96584839 0.79133175 ... 1.0019794  1.18343867 0.7878407 ]
 [0.89829719 0.8266452  1.0638819  ... 0.97193009 1.00040869 0.88099514]]


In [ ]:
x = np.array([1, 2, 3, 4, 5])
# delete the first and fifth element of x
x = np.delete(x, [0,4,1])
print('x = np.delete(x, [0,4,1]):\n',x)

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('\nY = np.array([[1,2,3],[4,5,6],[7,8,9]]):\n',Y)
w = np.delete(Y, 0, axis=0)
print('\nw = np.delete(Y, 0, axis=0):\n',w)
W = np.delete(Y, 0, axis=1)
print('\nW = np.delete(Y, 0, axis=1):\n',W)
v = np.delete(Y, [0,2], axis=1)
print('\nv = np.delete(Y, [0,2], axis=1):\n',v)

x = np.delete(x, [0,4,1]):
 [3 4]

Y = np.array([[1,2,3],[4,5,6],[7,8,9]]):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = np.delete(Y, 0, axis=0):
 [[4 5 6]
 [7 8 9]]

W = np.delete(Y, 0, axis=1):
 [[2 3]
 [5 6]
 [8 9]]

v = np.delete(Y, [0,2], axis=1):
 [[2]
 [5]
 [8]]


x = np.array([1, 2, 3, 4, 5])<br>
x = np.delete(x, [0,4,1])<br>
np.delete(array, indices) → removes elements at the specified indices.<br>

[0,4,1] → removes 1st (0), 5th (4), and then the original 2nd (1) element.<br>

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])<br>
Creates a 3×3 2D array.

w = np.delete(Y, 0, axis=0)<br>
Deletes row 0 (first row) because axis=0 → row-wise deletion.

W = np.delete(Y, 0, axis=1)<br>
Deletes column 0 (first column) because axis=1 → column-wise deletion.

v = np.delete(Y, [0,2], axis=1)<br>
Deletes columns 0 and 2 → keeps only the middle column.

In [ ]:
x = np.array([1, 2, 3, 4, 5])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.append(x, 6)
print('x = np.append(x, 6):\n',x)
x = np.append(x, [7,8])
print('\nx = np.append(x, [7,8]):\n',x)
v = np.append(Y, [[10,11,12]], axis=0)
print('\nv = np.append(Y, [[10,11,12]], axis=0):\n',v)
q = np.append(Y,[[13],[14],[15]], axis=1)
print('\nq = np.append(Y,[[13],[14],[15]], axis=1):\n',q)

x = np.append(x, 6):
 [1 2 3 4 5 6]

x = np.append(x, [7,8]):
 [1 2 3 4 5 6 7 8]

v = np.append(Y, [[10,11,12]], axis=0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

q = np.append(Y,[[13],[14],[15]], axis=1):
 [[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]]


In [ ]:
# Insert
# np.insert(ndarray, index, elements, axis)
# inserts the given list of elements to ndarray right before
# the given index along the specified axis
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])
# insert the integer 3 and 4 between 2 and 5 in x. here 2 is index at which it should be inserted
x = np.insert(x,2,[3,4])
print(x)
# insert a row between the first and last row of Y
w = np.insert(Y,1,[4,5,6],axis=0)
print(w)
# insert a column full of [5.6] between the first and second column of Y
v = np.insert(Y,1,[5,6], axis=1)
print(v)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 2 3]
 [7 6 8 9]]


In [ ]:
# Stacking
# NumPy also allows us to stack ndarrays on top of each other,
# or to stack them side by side. The stacking is done using either
# the np.vstack() function for vertical stacking, or the np.hstack()
# function for horizontal stacking. It is important to note that in
# order to stack ndarrays, the shape of the ndarrays must match.
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
z = np.vstack((x,Y)) # [[1,2], [3,4], [5,6]]
w = np.hstack((Y,x.reshape(2,1))) # [[3,4,1], [5,6,2]]

In [ ]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Extract elements along the diagonal
d0 = np.diag(X)
print(d0)
# As default is k=0, which refers to the main diagonal.
# Values of k > 0 are used to select elements in diagonals above
# the main diagonal, and values of k < 0 are used to select elements
# in diagonals below the main diagonal.
d1 = np.diag(X, k=1)
print(d1)
d2 = np.diag(X, k=-1)
print(d2)

[1 5 9]
[2 6]
[4 8]


In [ ]:
u = np.unique(X)
print(u)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [ ]:
# Sorting
# When used as a function, it doesn't change the original ndarray
s = np.sort(x)
print('s:\n',s)
# When used as a method, the original array will be sorted
x.sort()
print('\nx:\n',x)

x = np.array([1,2,3,4,5,4,3,2])
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# sort x but only keep the unique elements in x
s = np.sort(np.unique(x))
print('\ns unique:\n',s)
# sort the columns of X
s = np.sort(X, axis = 0)
print('\ns axis = 0:\n',s)
# sort the rows of X
s = np.sort(X, axis = 1)
print('\ns axis = 1:\n',s)

s = -np.sort(-X, axis = 0)
print('\n-s axis = 0:\n',s)
# sort the rows of X
s = -np.sort(-X, axis = 1)
print('\n-s axis = 1:\n',s)

s:
 [1 2 2 3 3 4 4 5]

x:
 [1 2 2 3 3 4 4 5]

s unique:
 [1 2 3 4 5]

s axis = 0:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

s axis = 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

-s axis = 0:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

-s axis = 1:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# NumPy allows element-wise operations on ndarrays as well as
# matrix operations. In order to do element-wise operations,
# NumPy sometimes uses something called Broadcasting.
# Broadcasting is the term used to describe how NumPy handles
# element-wise arithmetic operations with ndarrays of different shapes.
# For example, broadcasting is used implicitly when doing arithmetic
# operations between scalars and ndarrays.
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
print(np.add(x,y))
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)

# in order to do these operations the shapes of the ndarrays
# being operated on, must have the same shape or be broadcastable
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
np.add(X,Y)
np.subtract(X,Y)
np.multiply(X,Y)
np.divide(X,Y)

# apply mathematical functions to all elements of an ndarray at once
np.exp(x)
np.sqrt(x)
np.power(x,2)

[ 6.5  8.5 10.5 12.5]


array([ 1,  4,  9, 16])

In [ ]:
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Standard Deviation of all elements in X:', X.std())
print('Median of all elements in X:', np.median(X))
print('Maximum value of all elements in X:', X.max())
print('Minimum value of all elements in X:', X.min())

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Standard Deviation of all elements in X: 1.118033988749895
Median of all elements in X: 2.5
Maximum value of all elements in X: 4
Minimum value of all elements in X: 1


In [ ]:
# Broadcasting
# NumPy is working behind the scenes to broadcast 3 along the ndarray
# so that they have the same shape. This allows us to add 3 to each
# element of X with just one line of code.
print(4*X)
print(4+X)
print(4-X)
print(4/X)
# NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays
# by broadcasting the smaller ndarrays along the big ndarray so that
# they have compatible shapes. In general, NumPy can do this provided
# that the smaller ndarray can be expanded to the shape of the larger
# ndarray in such a way that the resulting broadcast is unambiguous.
x = np.array([1,2,3])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z = np.array([1,2,3]).reshape(3,1)
print(x + Y)
print(Z + Y)

[[ 4  8]
 [12 16]]
[[5 6]
 [7 8]]
[[3 2]
 [1 0]]
[[4.         2.        ]
 [1.33333333 1.        ]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


# **PANDAS**